<?php
declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: lmh <lmh@weiyian.com>
 */

namespace app\components\decorator;


class Car extends Decorate
{
    public function display()
    {
        echo "<br/>i have a car";
        parent::display(); // TODO: Change the autogenerated stub
    }

}
