<?php
declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: lmh
 */

namespace app\controllers;


use app\components\annotations\Logger;
use app\components\dependencies\ClassFactory;
use app\components\drivers\AnnotationDriver;
use app\components\factory\MessageFactory;
use app\components\proxy\Client;
use app\components\strategy\AStrategy;
use app\components\strategy\Context;
use app\models\Circle;
use app\models\User;
use app\services\UserService;
use Doctrine\Annotations\AnnotationException;
use EmailMessage;
use ReflectionClass;
use SmsMessage;
use yii\base\UserException;
use yii\web\Controller;

class IndexController extends Controller
{
    /**
     * @param $action
     * @return bool
     * @throws \ReflectionException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        try {
            $driver = new AnnotationDriver();
            $driver->loadMetadataForMethod(IndexController::class, $action->actionMethod);
        } catch (AnnotationException $e) {
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }


    /**
     * 基础概念
     * @throws \ReflectionException
     */
    public function actionReflection()
    {
        $user = new User();
        $ref = new ReflectionClass(User::class);
        var_dump($ref->getMethods());

        $method = $ref->getMethod('setName');
        $method->invoke($user, 'zhangshan');

        $method = $ref->getMethod('getName');
        $method->setAccessible(true);
        $data = $method->invoke($user);

        var_dump($data);


        $m = new \ReflectionMethod(User::class, 'getName');


        var_dump($m);

    }


    /**
     * 策略模式理解
     * @throws UserException
     */
    public function actionStrategy()
    {
//        if($a == 'a'){
//            //dosomething
//        }else if($a == 'b'){
//            //doshomething
//        }else if($a == 'c'){
//            //doshomething
//        } else{
//            ////doshomething
//        }

        $a = 'A';
        if ($a == 'A') {
            $strategy = new AStrategy();
        } elseif ($a == 'B') {
            $strategy = new AStrategy();
        } else {
            throw new UserException('暂无');
        }
        echo $strategy->show();

    }

    /**
     * 反射改造策略模式应用
     * @throws UserException
     */
    public function actionStrategyReflection()
    {
        $a = 'A';
//        $strategy = Context::getInstance('app\\components\\strategy\\' . $a . 'Strategy');
        $strategy = Context::getInstance($a);
        echo $strategy->show();
    }

    /**
     * 反射注解应用
     * @Logger("我是日志")
     */
    public function actionAnnotation()
    {
        var_dump('dsd');
    }

    /**
     * 依赖注入应用
     * @throws \ReflectionException
     */
    public function actionDependencies()
    {
        /**
         * @var Circle $circle
         */
        $circle = ClassFactory::make(Circle::class);
        $area = $circle->area();
        var_dump($area);
    }

    public function actionDependenciesReflection()
    {

    }

    /**
     * 代理
     * @author lmh
     */
    public function actionRequest()
    {
        /**
         * @var $userService UserService
         */
        $userService = new Client(UserService::class);
        var_export($userService->getUserInfo(104));
    }

    /**
     * 发送消息普通方式
     * @author lmh
     * @throws UserException
     */
    public function actionMessage()
    {
        $mes_type = 'Sms';

        switch ($mes_type) {
            case 'Sms':
                $obj = new SmsMessage();
                break;
            case 'Email':
                $obj = new EmailMessage();
                break;
            default:
                throw new UserException('NO Message Type Found');
        }
        $obj->send();
    }

    /**
     * 发送消息-工厂方式改造
     * @author lmh
     * @throws \yii\base\UserException
     */
    public function actionFactory()
    {
        $obj = MessageFactory::getInstance('sms');
        $obj->send();
    }

    /**
     * 利用反射-改造工厂方式
     * @author lmh
     */
    public function actionFactoryReflection()
    {
        try {
            $obj = MessageFactory::geReflection('sms');
            $obj->send();
        } catch (\ReflectionException $e) {
        }
    }
}